---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: ops
  name: kopf-svc-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kopf-role-cluster
rules:
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]
   
   ### Cluster role for CRD
  - apiGroups: ["itoutposts.com"]
    resources: ["envinjectors"]
    verbs: ["*"]
  
  - apiGroups: ["apps"]
    resources: ["deployments","deployments/status"]
    verbs: ["*"]
  
  - apiGroups: [""]
    resources: ["events","deployments","pods","namespaces","deployments/status"]
    verbs: ["list","watch","get","patch","create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kopf-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kopf-role-cluster
subjects:
  - kind: ServiceAccount
    name: kopf-svc-account
    namespace: ops